name: Run tests
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.9"
    - name: install dependencies
      run: uv sync --locked
    - name: run tests
      run: ./runtests.sh
